usager_list:
  path: /api/usagers
  controller: App\Controller\UsagerController::list

show_usager:
  path: /api/usagers/{id}
  controller: App\Controller\UsagerController::show

searchByNum_Acc_usagers:
  path: /api/usagers/num_acc/{num_acc}
  controller: App\Controller\UsagerController::searchByNum_Acc

caracteristique_list:
  path: /api/caracteristiques
  controller: App\Controller\CaracteristiqueController::list

show_caracterisque:
  path: /api/caracteristiques/{id}
  controller: App\Controller\CaracteristiqueController::show
  methods: GET

searchByNum_Acc_caracteristiques:
  path: /api/caracteristiques/num_acc/{num_acc}
  controller: App\Controller\CaracteristiqueController::searchByNum_Acc

lieux_list:
  path: /api/lieux
  controller: App\Controller\LieuxController::list

show_lieux:
  path: /api/lieux/{id}
  controller: App\Controller\LieuxController::show

searchByNum_Acc_lieux:
  path: /api/lieux/num_acc/{num_acc}
  controller: App\Controller\LieuxController::searchByNum_Acc

vehicule_list:
  path: /api/vehicules
  controller: App\Controller\VehiculeController::list

show_vehicule:
  path: /api/vehicules/{id}
  controller: App\Controller\VehiculeController::show

searchByNum_Acc_vehicule:
  path: /api/vehicules/num_acc/{num_acc}
  controller: App\Controller\VehiculeController::searchByNum_Acc

Accident_File_Json:
  path: /api/accidents/json/{num_acc}
  controller: App\Controller\AccidentController::getAccidentJsonFile

Accident_File_Csv:
  path: /api/accidents/csv/{num_acc}
  controller: App\Controller\AccidentController::getAccidentCsvFile

uploadCsvFileVehicule:
  path: /api/vehicules/new
  controller: App\Controller\VehiculeController::new

uploadCsvFileUsagers:
  path: /api/usagers/new
  controller: App\Controller\UsagersController::new

uploadCsvFileCaracteristques:
  path: /api/caracteristiques/new
  controller: App\Controller\CaracteristiqueController::new
  methods: POST

uploadCsvFileLieux:
  path: /api/lieux/new
  controller: App\Controller\LieuxController::new

getPaginatedReccordsCaracteristiques:
  path: /api/caracteristiques/paginated/{row_index}
  controller: App\Controller\CaracteristiqueController::getPaginatedReccords
getPaginatedReccordsCaracteristiquesCsv:
  path: /api/caracteristiques/paginated_csv/{row_index}
  controller: App\Controller\CaracteristiqueController::getPaginatedReccordsCsv
getPaginatedReccordsCaracteristiquesJson:
  path: /api/caracteristiques/paginated_json/{row_index}
  controller: App\Controller\CaracteristiqueController::getPaginatedReccordsJson

getPaginatedReccordsLieux:
  path: /api/lieux/paginated/{row_index}
  controller: App\Controller\LieuxController::getPaginatedReccords
getPaginatedReccordsLieuxCsv:
  path: /api/lieux/paginated_csv/{row_index}
  controller: App\Controller\LieuxController::getPaginatedReccordsCsv
getPaginatedReccordsLieuxJson:
  path: /api/lieux/paginated_json/{row_index}
  controller: App\Controller\LieuxController::getPaginatedReccordsJson

getPaginatedReccordsUsagers:
  path: /api/usagers/paginated/{row_index}
  controller: App\Controller\UsagerController::getPaginatedReccords
getPaginatedReccordsUsagersCsv:
  path: /api/usagers/paginated_csv/{row_index}
  controller: App\Controller\UsagerController::getPaginatedReccordsCsv
getPaginatedReccordsUsagersJson:
  path: /api/usagers/paginated_json/{row_index}
  controller: App\Controller\UsagerController::getPaginatedReccordsJson

getPaginatedReccordsVehicules:
  path: /api/vehicules/paginated/{row_index}
  controller: App\Controller\VehiculeController::getPaginatedReccords
getPaginatedReccordsVehiculesCsv:
  path: /api/vehicules/paginated_csv/{row_index}
  controller: App\Controller\VehiculeController::getPaginatedReccordsCsv
getPaginatedReccordsVehiculesJson:
  path: /api/vehicules/paginated_json/{row_index}
  controller: App\Controller\VehiculeController::getPaginatedReccordsJson
