usager_list:
  path: /usagers
  controller: App\Controller\UsagerController::list

show_usager:
  path: /usagers/{id}
  controller: App\Controller\UsagerController::show

searchByNum_Acc_usagers:
  path: /usagers/num_acc/{num_Acc}
  controller: App\Controller\UsagerController::searchByNum_Acc

caracteristique_list:
  path: /caracteristiques
  controller: App\Controller\CaracteristiqueController::list

show_caracterisque:
  path: /caracteristiques/{id}
  controller: App\Controller\CaracteristiqueController::show

searchByNum_Acc_caracteristiques:
  path: /caracteristiques/num_acc/{num_Acc}
  controller: App\Controller\CaracteristiqueController::searchByNum_Acc

lieux_list:
  path: /lieux
  controller: App\Controller\LieuxController::list

show_lieux:
  path: /lieux/{id}
  controller: App\Controller\LieuxController::show

searchByNum_Acc_lieux:
  path: /lieux/num_acc/{num_Acc}
  controller: App\Controller\LieuxController::searchByNum_Acc

vehicule_list:
  path: /vehicules
  controller: App\Controller\VehiculeController::list

show_vehicule:
  path: /vehicules/{id}
  controller: App\Controller\VehiculeController::show

searchByNum_Acc_vehicule:
  path: /vehicules/num_acc/{num_Acc}
  controller: App\Controller\VehiculeController::searchByNum_Acc

Accident_File_Json:
  path: /accidents/json/{num_Acc}
  controller: App\Controller\AccidentController::getAccidentJsonFile

Accident_File_Csv:
  path: /accidents/csv/{num_Acc}
  controller: App\Controller\AccidentController::getAccidentCsvFile

uploadCsvFileVehicule:
  path: /vehicules/new
  controller: App\Controller\VehiculeController::new

uploadCsvFileUsagers:
  path: /usagers/new
  controller: App\Controller\UsagersController::new

uploadCsvFileCaracteristques:
  path: /caracteristiques/new
  controller: App\Controller\CaracteristiquesController::new

uploadCsvFileLieux:
  path: /lieux/new
  controller: App\Controller\LieuxController::new

getPaginatedReccordsCaracteristiques:
  path: /caracteristiques/paginated/{row_index}
  controller: App\Controller\CaracteristiqueController::getPaginatedReccords
getPaginatedReccordsCaracteristiquesCsv:
  path: /caracteristiques/paginated_csv/{row_index}
  controller: App\Controller\CaracteristiqueController::getPaginatedReccordsCsv
getPaginatedReccordsCaracteristiquesJson:
  path: /caracteristiques/paginated_json/{row_index}
  controller: App\Controller\CaracteristiqueController::getPaginatedReccordsJson

getPaginatedReccordsLieux:
  path: /lieux/paginated/{row_index}
  controller: App\Controller\LieuxController::getPaginatedReccords
getPaginatedReccordsLieuxCsv:
  path: /lieux/paginated_csv/{row_index}
  controller: App\Controller\LieuxController::getPaginatedReccordsCsv
getPaginatedReccordsLieuxJson:
  path: /lieux/paginated_json/{row_index}
  controller: App\Controller\LieuxController::getPaginatedReccordsJson

getPaginatedReccordsUsagers:
  path: /usagers/paginated/{row_index}
  controller: App\Controller\UsagersController::getPaginatedReccords
getPaginatedReccordsUsagersCsv:
  path: /usagers/paginated_csv/{row_index}
  controller: App\Controller\UsagersController::getPaginatedReccordsCsv
getPaginatedReccordsUsagersJson:
  path: /usagers/paginated_json/{row_index}
  controller: App\Controller\UsagersController::getPaginatedReccordsJson
