usager_list:
  path: /usagers
  controller: App\Controller\UsagerController::list

show_usager:
  path: /usagers/{id}
  controller: App\Controller\UsagerController::show

caracteristique_list:
  path: /caracterisques
  controller: App\Controller\CaracteristiqueController::list

show_caracterisque:
  path: /caracterisques/{id}
  controller: App\Controller\CaracteristiqueController::show

lieux_list:
  path: /lieux
  controller: App\Controller\LieuxController::list

show_lieux:
  path: /lieux/{id}
  controller: App\Controller\LieuxController::show

vehicule_list:
  path: /vehicules
  controller: App\Controller\VehiculeController::list

show_vehicule:
  path: /vehicules/{id}
  controller: App\Controller\VehiculeController::show
